// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rifiifbgjruiyudfyfda.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZmlpZmJnanJ1aXl1ZGZ5ZmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2MjY2MDIsImV4cCI6MjA0ODIwMjYwMn0.WLcTEVyWufsSOm1VgJBWk0nW143wRT4web0Akhm_I7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);